import type {
  ActionPhase,
  Assessment,
  Cockpit,
  ExtractedFact,
  Recommendation,
  Scenario,
  Source,
  TruthLayer,
} from "./types";

// Demo industrial manufacturing company used to seed the workbench.
// All amounts in absolute ₹ (₹1 Cr = 10_000_000).

const CR = 10_000_000;
const L = 100_000;

const now = () => new Date("2026-01-15T10:00:00.000Z").toISOString();
const ago = (hours: number) =>
  new Date(Date.parse("2026-01-15T10:00:00.000Z") - hours * 3600 * 1000).toISOString();

export const demoAssessment: Assessment = {
  id: "asm-bharat-heavy-fabrications",
  companyName: "Bharat Heavy Fabrications Pvt Ltd",
  industry: "industrial_manufacturing",
  objective: "board_review",
  revenueTarget: 150 * CR,
  marginTarget: 26,
  cashTarget: 25 * CR,
  headcountProductivityTarget: 32 * L,
  status: "analysis",
  createdAt: ago(72),
  updatedAt: now(),
};

export const demoSources: Source[] = [
  {
    id: "src-fy25-audit",
    assessmentId: demoAssessment.id,
    name: "FY25 Audited Financials",
    type: "financial_filing",
    status: "parsed",
    confidence: "high",
    notes: "Audited consolidated P&L and balance sheet for FY24-25.",
    createdAt: ago(60),
    pageCount: 42,
  },
  {
    id: "src-board-deck",
    assessmentId: demoAssessment.id,
    name: "FY26 Board Strategy Deck v3",
    type: "strategy_deck",
    status: "parsed",
    confidence: "high",
    notes: "Strategy plan with revenue, margin, and capex targets approved by the board.",
    createdAt: ago(58),
    pageCount: 28,
  },
  {
    id: "src-sop-quote-approval",
    assessmentId: demoAssessment.id,
    name: "SOP & Readiness Evidence Register — Sample",
    type: "sop",
    status: "parsed",
    confidence: "high",
    notes:
      "Sample quote approval matrix plus an initial gap review for ISO readiness, technical standards mapping, statutory documents, vendor onboarding, and AI output approvals.",
    createdAt: ago(48),
    pageCount: 4,
  },
  {
    id: "src-excel-pipeline",
    assessmentId: demoAssessment.id,
    name: "Pipeline Tracker — Jan 2026",
    type: "excel_tracker",
    status: "parsed",
    confidence: "medium",
    notes: "Sales team tracker maintained by Sales Ops.",
    createdAt: ago(36),
    pageCount: 1,
  },
  {
    id: "src-erp-finance-export",
    assessmentId: demoAssessment.id,
    name: "ERP — Finance Q3 Export",
    type: "erp_export",
    status: "parsed",
    confidence: "high",
    notes: "GL and AR/AP extracts for Oct–Dec 2025.",
    createdAt: ago(24),
    pageCount: 18,
  },
  {
    id: "src-crm-export",
    assessmentId: demoAssessment.id,
    name: "CRM — Opportunities Export",
    type: "crm_export",
    status: "parsed",
    confidence: "high",
    notes: "Open opportunities, stage, close date, owner.",
    createdAt: ago(24),
    pageCount: 6,
  },
  {
    id: "src-proposal-log",
    assessmentId: demoAssessment.id,
    name: "Proposal Submission Log Q3",
    type: "proposal_report",
    status: "parsed",
    confidence: "medium",
    notes: "Internal log of proposals submitted in Oct–Dec 2025.",
    createdAt: ago(20),
    pageCount: 2,
  },
  {
    id: "src-operations-q3",
    assessmentId: demoAssessment.id,
    name: "Operations — Q3 Plant Report",
    type: "operations_report",
    status: "parsed",
    confidence: "medium",
    notes: "Production, OEE, downtime summary for the quarter.",
    createdAt: ago(12),
    pageCount: 8,
  },
];

export const demoFacts: ExtractedFact[] = [
  {
    id: "fact-rev-fy25",
    assessmentId: demoAssessment.id,
    sourceId: "src-fy25-audit",
    kind: "revenue",
    label: "FY25 actual revenue",
    value: "₹120 Cr",
    numericValue: 120 * CR,
    unit: "₹",
    evidence: "P&L FY25: revenue from operations = ₹120.0 Cr",
    confidence: "high",
    capturedAt: ago(60),
  },
  {
    id: "fact-rev-target-fy26",
    assessmentId: demoAssessment.id,
    sourceId: "src-board-deck",
    kind: "target",
    label: "FY26 strategy revenue target",
    value: "₹150 Cr",
    numericValue: 150 * CR,
    unit: "₹",
    evidence: "Board deck p.4: 'Revenue target FY26 = ₹150 Cr'",
    confidence: "high",
    capturedAt: ago(58),
  },
  {
    id: "fact-rev-forecast-fy26",
    assessmentId: demoAssessment.id,
    sourceId: "src-erp-finance-export",
    kind: "revenue",
    label: "FY26 run-rate forecast",
    value: "₹134 Cr",
    numericValue: 134 * CR,
    unit: "₹",
    evidence: "Q3 run-rate × 4 = ₹134 Cr, finance forecast 15-Jan",
    confidence: "medium",
    capturedAt: ago(24),
  },
  {
    id: "fact-gm-actual",
    assessmentId: demoAssessment.id,
    sourceId: "src-fy25-audit",
    kind: "margin",
    label: "FY25 gross margin",
    value: "21%",
    numericValue: 21,
    unit: "%",
    evidence: "P&L FY25: gross margin = 21.0%",
    confidence: "high",
    capturedAt: ago(60),
  },
  {
    id: "fact-gm-target",
    assessmentId: demoAssessment.id,
    sourceId: "src-board-deck",
    kind: "target",
    label: "FY26 target gross margin",
    value: "26%",
    numericValue: 26,
    unit: "%",
    evidence: "Board deck p.6: 'GM target 26%'",
    confidence: "high",
    capturedAt: ago(58),
  },
  {
    id: "fact-receivables",
    assessmentId: demoAssessment.id,
    sourceId: "src-erp-finance-export",
    kind: "receivables",
    label: "Receivables outstanding",
    value: "₹18 Cr",
    numericValue: 18 * CR,
    unit: "₹",
    evidence: "AR aging 31-Dec-2025 = ₹18.0 Cr",
    confidence: "high",
    capturedAt: ago(24),
  },
  {
    id: "fact-backlog",
    assessmentId: demoAssessment.id,
    sourceId: "src-erp-finance-export",
    kind: "backlog",
    label: "Order backlog",
    value: "₹42 Cr",
    numericValue: 42 * CR,
    unit: "₹",
    evidence: "Open SO backlog at 31-Dec-2025 = ₹42.0 Cr",
    confidence: "high",
    capturedAt: ago(24),
  },
  {
    id: "fact-pipeline",
    assessmentId: demoAssessment.id,
    sourceId: "src-crm-export",
    kind: "pipeline",
    label: "CRM open pipeline",
    value: "₹38 Cr",
    numericValue: 38 * CR,
    unit: "₹",
    evidence: "CRM opportunities export: total pipeline = ₹38 Cr",
    confidence: "medium",
    capturedAt: ago(24),
  },
  {
    id: "fact-winrate-actual",
    assessmentId: demoAssessment.id,
    sourceId: "src-proposal-log",
    kind: "orders",
    label: "Current proposal win rate",
    value: "24%",
    numericValue: 24,
    unit: "%",
    evidence: "Q3 proposal log: 6 won / 25 submitted = 24%",
    confidence: "medium",
    capturedAt: ago(20),
  },
  {
    id: "fact-winrate-required",
    assessmentId: demoAssessment.id,
    sourceId: "src-board-deck",
    kind: "target",
    label: "Required win rate to hit revenue plan",
    value: "31%",
    numericValue: 31,
    unit: "%",
    evidence: "Board deck p.9: 'Required win rate 31%'",
    confidence: "high",
    capturedAt: ago(58),
  },
  {
    id: "fact-headcount",
    assessmentId: demoAssessment.id,
    sourceId: "src-operations-q3",
    kind: "headcount",
    label: "Headcount",
    value: "420",
    numericValue: 420,
    unit: "people",
    evidence: "Operations Q3 report: total headcount = 420",
    confidence: "high",
    capturedAt: ago(12),
  },
  {
    id: "fact-inventory",
    assessmentId: demoAssessment.id,
    sourceId: "src-erp-finance-export",
    kind: "cost",
    label: "Inventory carrying value",
    value: "₹22 Cr",
    numericValue: 22 * CR,
    unit: "₹",
    evidence: "Inventory GL 31-Dec-2025 = ₹22.0 Cr",
    confidence: "high",
    capturedAt: ago(24),
  },
  {
    id: "fact-cust-concentration",
    assessmentId: demoAssessment.id,
    sourceId: "src-fy25-audit",
    kind: "customer",
    label: "Top 5 customer concentration",
    value: "62% of revenue",
    numericValue: 62,
    unit: "%",
    evidence: "FY25 audit schedule: top 5 customers = 62% of revenue",
    confidence: "high",
    capturedAt: ago(60),
  },
  {
    id: "fact-delayed-proposals",
    assessmentId: demoAssessment.id,
    sourceId: "src-proposal-log",
    kind: "risk",
    label: "Delayed proposals",
    value: "4 proposals worth ₹6.2 Cr overdue",
    numericValue: 6.2 * CR,
    unit: "₹",
    evidence: "Q3 proposal log: 4 proposals >30 days past expected close, total ₹6.2 Cr",
    confidence: "medium",
    capturedAt: ago(20),
  },
  {
    id: "fact-low-margin-products",
    assessmentId: demoAssessment.id,
    sourceId: "src-excel-pipeline",
    kind: "product",
    label: "Low-margin product lines",
    value: "3 product lines under 12% GM",
    numericValue: 3,
    unit: "count",
    evidence: "Pipeline tracker margin column: 3 SKUs flagged <12% GM",
    confidence: "medium",
    capturedAt: ago(36),
  },
  {
    id: "fact-supplier-risk",
    assessmentId: demoAssessment.id,
    sourceId: "src-erp-finance-export",
    kind: "supplier",
    label: "Supplier cost escalations",
    value: "2 suppliers with >8% QoQ cost increase",
    numericValue: 2,
    unit: "count",
    evidence: "AP variance report Q3: 2 suppliers flagged with >8% cost increase",
    confidence: "medium",
    capturedAt: ago(24),
  },
  {
    id: "fact-sop-violation",
    assessmentId: demoAssessment.id,
    sourceId: "src-sop-quote-approval",
    kind: "sop_rule",
    label: "SOP violation — quote approval",
    value: "Quotes >₹50L missing approval matrix sign-off",
    numericValue: 50 * L,
    unit: "₹",
    evidence: "SOP §3.2 + ERP audit log: 7 quotes >₹50L without required sign-off in Q3",
    confidence: "high",
    capturedAt: ago(48),
  },
  {
    id: "fact-action-board",
    assessmentId: demoAssessment.id,
    sourceId: "src-board-deck",
    kind: "action_item",
    label: "Board action: improve win rate",
    value: "Board mandates +7pp win rate improvement in FY26",
    evidence: "Board deck p.11: action item B-26-04",
    confidence: "high",
    capturedAt: ago(58),
  },
  {
    id: "fact-commitment",
    assessmentId: demoAssessment.id,
    sourceId: "src-board-deck",
    kind: "commitment",
    label: "Management commitment",
    value: "Promoter committed ₹4 Cr working-capital injection",
    numericValue: 4 * CR,
    unit: "₹",
    evidence: "Board deck p.13: working capital support ₹4 Cr",
    confidence: "high",
    capturedAt: ago(58),
  },
  {
    id: "fact-rpe-target",
    assessmentId: demoAssessment.id,
    sourceId: "src-board-deck",
    kind: "target",
    label: "Revenue per employee target",
    value: "₹32 L / employee",
    numericValue: 32 * L,
    unit: "₹/employee",
    evidence: "Board deck p.7: 'RPE target ₹32L'",
    confidence: "high",
    capturedAt: ago(58),
  },
];

export const demoTruthLayers: TruthLayer[] = [
  {
    key: "financial",
    title: "Financial Truth",
    description:
      "P&L, balance sheet, working capital, and unit economics reconciled across entities, plants, and SKUs.",
    confidence: "high",
    evidence: [
      {
        sourceId: "src-fy25-audit",
        factId: "fact-rev-fy25",
        excerpt: "P&L FY25: revenue from operations = ₹120.0 Cr",
      },
      {
        sourceId: "src-erp-finance-export",
        factId: "fact-receivables",
        excerpt: "AR aging 31-Dec-2025 = ₹18.0 Cr",
      },
      {
        sourceId: "src-erp-finance-export",
        factId: "fact-inventory",
        excerpt: "Inventory GL 31-Dec-2025 = ₹22.0 Cr",
      },
    ],
    findings: [
      {
        id: "fnd-fin-1",
        text: "FY25 actual revenue ₹120 Cr vs FY26 strategy target ₹150 Cr — 20% growth gap.",
        impact: "high",
        factIds: ["fact-rev-fy25", "fact-rev-target-fy26"],
      },
      {
        id: "fnd-fin-2",
        text: "FY26 run-rate forecast ₹134 Cr is 11% below the ₹150 Cr strategy target.",
        impact: "high",
        factIds: ["fact-rev-forecast-fy26", "fact-rev-target-fy26"],
      },
      {
        id: "fnd-fin-3",
        text: "FY25 gross margin 21% is 5pp below the FY26 target of 26%.",
        impact: "high",
        factIds: ["fact-gm-actual", "fact-gm-target"],
      },
      {
        id: "fnd-fin-4",
        text: "Top 5 customers are 62% of revenue — meaningful concentration risk.",
        impact: "medium",
        factIds: ["fact-cust-concentration"],
      },
    ],
    gaps: [
      "Unit economics per SKU not available in ERP export.",
      "Customer-level profitability not available in source set.",
    ],
    contradictions: [],
  },
  {
    key: "strategic",
    title: "Proposal and Revenue Truth",
    description:
      "Revenue ambition, pipeline, proposal controls, customer prequalification readiness, and commercial commitments reconciled to evidence.",
    confidence: "high",
    evidence: [
      {
        sourceId: "src-board-deck",
        factId: "fact-rev-target-fy26",
        excerpt: "Board deck p.4: 'Revenue target FY26 = ₹150 Cr'",
      },
      {
        sourceId: "src-board-deck",
        factId: "fact-action-board",
        excerpt: "Board deck p.11: action item B-26-04",
      },
    ],
    findings: [
      {
        id: "fnd-str-1",
        text: "Strategy plan commits to ₹150 Cr revenue and 26% gross margin in FY26.",
        impact: "high",
        factIds: ["fact-rev-target-fy26", "fact-gm-target"],
      },
      {
        id: "fnd-str-2",
        text: "Required proposal win rate of 31% is 7pp above the current 24% — explicit board action item.",
        impact: "high",
        factIds: ["fact-winrate-actual", "fact-winrate-required", "fact-action-board"],
      },
      {
        id: "fnd-str-3",
        text: "Promoter has committed ₹4 Cr working-capital injection — supports cash position.",
        impact: "medium",
        factIds: ["fact-commitment"],
      },
      {
        id: "fnd-str-4",
        text: "Customer prequalification and technical standards evidence is not linked to the proposal workflow in the current source set.",
        impact: "high",
        factIds: ["fact-winrate-actual", "fact-sop-violation"],
      },
    ],
    gaps: [
      "Customer prequalification pack and vendor registration status are not included in the source set.",
      "API / ASME / ANSI / IEC / ISA and customer-specific requirements are not mapped to proposal checkpoints.",
    ],
    contradictions: [
      "Strategy growth target implies pricing/mix changes not visible in current pipeline mix.",
    ],
  },
  {
    key: "operational",
    title: "Operational, Vendor, and Capacity Truth",
    description:
      "Production, quality, logistics, supplier qualification, subcontractor governance, talent, capacity, downtime, and OEE.",
    confidence: "medium",
    evidence: [
      {
        sourceId: "src-operations-q3",
        factId: "fact-headcount",
        excerpt: "Operations Q3 report: total headcount = 420",
      },
      {
        sourceId: "src-erp-finance-export",
        factId: "fact-backlog",
        excerpt: "Open SO backlog at 31-Dec-2025 = ₹42.0 Cr",
      },
    ],
    findings: [
      {
        id: "fnd-ops-1",
        text: "Order backlog ₹42 Cr provides 4 months of revenue visibility at FY25 run-rate.",
        impact: "medium",
        factIds: ["fact-backlog"],
      },
      {
        id: "fnd-ops-2",
        text: "Inventory ₹22 Cr alongside ₹18 Cr receivables represents ₹40 Cr working-capital deployment.",
        impact: "medium",
        factIds: ["fact-inventory", "fact-receivables"],
      },
      {
        id: "fnd-ops-3",
        text: "4 proposals worth ₹6.2 Cr are delayed beyond expected close — execution risk in Q4.",
        impact: "high",
        factIds: ["fact-delayed-proposals"],
      },
      {
        id: "fnd-ops-4",
        text: "Supplier cost escalations are visible, but qualification status, onboarding documents, and subcontractor governance evidence are not.",
        impact: "high",
        factIds: ["fact-supplier-risk"],
      },
    ],
    gaps: [
      "OEE and downtime data not in current source set — would need MES export.",
      "Supplier qualification, vendor registration, and subcontractor governance tracker not provided.",
      "Role capacity and critical-skill coverage are not mapped to delivery demand.",
    ],
    contradictions: [],
  },
  {
    key: "process",
    title: "Compliance and Standards Truth",
    description:
      "ISO and technical standards mapping, statutory documents, audit evidence, SOP controls, and documentation readiness.",
    confidence: "medium",
    evidence: [
      {
        sourceId: "src-sop-quote-approval",
        factId: "fact-sop-violation",
        excerpt: "SOP §3.2 + ERP audit log: 7 quotes >₹50L without required sign-off in Q3",
      },
    ],
    findings: [
      {
        id: "fnd-pro-1",
        text: "7 quotes above ₹50L in Q3 went out without the required approval sign-off — SOP violation pattern.",
        impact: "high",
        factIds: ["fact-sop-violation"],
      },
      {
        id: "fnd-pro-2",
        text: "The sample evidence register has no complete mapping for ISO 9001, ISO 14001, ISO 45001, ISO/IEC 27001, ISO/IEC 42001, or ISO 50001 applicability.",
        impact: "high",
        factIds: ["fact-sop-violation"],
      },
      {
        id: "fnd-pro-3",
        text: "Statutory document status, audit evidence ownership, and customer technical standards mapping are not controlled in one readiness register.",
        impact: "high",
        factIds: ["fact-sop-violation"],
      },
    ],
    gaps: [
      "ISO readiness evidence register requires owner, evidence status, gap, and next-review fields.",
      "API / ASME / ANSI / IEC / ISA and customer-specific standards mapping is incomplete.",
      "Statutory document and audit evidence dashboard not provided.",
    ],
    contradictions: [
      "SOP says quotes >₹50L need approval; ERP log shows this is being bypassed.",
    ],
  },
  {
    key: "collaboration",
    title: "AI Governance and Accountability Truth",
    description:
      "Human validation, source traceability, prompt/output review, approvals, policy controls, role-based access, and audit trails.",
    confidence: "low",
    evidence: [],
    findings: [],
    gaps: [
      "No documented human-in-the-loop validation workflow for AI-generated findings.",
      "Prompt/output review, source traceability, approval history, and audit trail evidence are incomplete.",
      "No autonomous irreversible action is permitted, but the policy control and exception process are not documented.",
    ],
    contradictions: [],
  },
];

export const demoCockpit: Cockpit = {
  metrics: [
    {
      key: "revenue",
      label: "Revenue actual vs target",
      value: 120 * CR,
      target: 150 * CR,
      unit: "₹",
      status: "off_track",
      note: "FY25 actual 120 Cr; FY26 strategy target 150 Cr; current run-rate 134 Cr.",
    },
    {
      key: "margin",
      label: "Margin actual vs target",
      value: 21,
      target: 26,
      unit: "%",
      status: "at_risk",
      note: "FY25 gross margin 21%; FY26 target 26%; 5pp gap driven by mix and supplier cost.",
    },
    {
      key: "cash",
      label: "Cash risk",
      value: 18 * CR,
      target: 25 * CR,
      unit: "₹",
      status: "at_risk",
      note: "Receivables ₹18 Cr + inventory ₹22 Cr = ₹40 Cr working capital tied up.",
    },
    {
      key: "receivables",
      label: "Receivables risk",
      value: 18 * CR,
      target: 12 * CR,
      unit: "₹",
      status: "at_risk",
      note: "AR is 15% of FY25 revenue; DSO at 55 days vs 35-day target.",
    },
    {
      key: "pipeline",
      label: "Pipeline gap",
      value: 38 * CR,
      target: 50 * CR,
      unit: "₹",
      status: "at_risk",
      note: "Open pipeline ₹38 Cr vs required ₹50 Cr to hit FY26 plan.",
    },
    {
      key: "backlog",
      label: "Order backlog",
      value: 42 * CR,
      target: 45 * CR,
      unit: "₹",
      status: "on_track",
      note: "Open SO backlog ₹42 Cr provides 4 months of revenue visibility.",
    },
    {
      key: "rpe",
      label: "Revenue per employee",
      value: (120 * CR) / 420,
      target: 32 * L,
      unit: "₹/employee",
      status: "off_track",
      note: "₹28.6L per employee actual vs ₹32L target.",
    },
    {
      key: "winrate",
      label: "Proposal win rate",
      value: 24,
      target: 31,
      unit: "%",
      status: "off_track",
      note: "Q3 win rate 24% vs 31% required to hit FY26 plan.",
    },
    {
      key: "standards_readiness_gaps",
      label: "Standards readiness gaps",
      value: 7,
      target: 0,
      unit: "count",
      status: "off_track",
      note:
        "Sample gap review: ISO and customer technical standards mappings need evidence owners and closure dates.",
    },
    {
      key: "audit_evidence_completeness",
      label: "Audit evidence completeness",
      value: 42,
      target: 100,
      unit: "%",
      status: "off_track",
      note:
        "Sample evidence-status indicator based on the demo readiness register; not an audit opinion.",
    },
    {
      key: "vendor_qualification_gaps",
      label: "Vendor qualification gaps",
      value: 5,
      target: 0,
      unit: "count",
      status: "off_track",
      note:
        "Sample gaps across supplier qualification, onboarding documents, and subcontractor governance.",
    },
    {
      key: "customer_prequalification_readiness",
      label: "Customer prequalification readiness",
      value: 48,
      target: 100,
      unit: "%",
      status: "off_track",
      note:
        "Sample documentation readiness coverage; this does not represent customer approval.",
    },
    {
      key: "ai_output_validation_coverage",
      label: "AI output validation coverage",
      value: 35,
      target: 100,
      unit: "%",
      status: "off_track",
      note:
        "Sample coverage of human review checkpoints for AI-generated findings and recommendations.",
    },
    {
      key: "source_traceability_coverage",
      label: "Source traceability coverage",
      value: 70,
      target: 100,
      unit: "%",
      status: "at_risk",
      note:
        "Sample share of displayed findings linked to a source and evidence reference.",
    },
    {
      key: "approval_workflow_coverage",
      label: "Approval workflow coverage",
      value: 40,
      target: 100,
      unit: "%",
      status: "off_track",
      note:
        "Sample coverage for review, approval, exception handling, and audit trail checkpoints.",
    },
  ],
  topRisks: [
    {
      id: "risk-winrate",
      title: "Win rate gap of 7pp",
      description: "Current 24% vs required 31% — largest single driver of the revenue gap.",
      likelihood: "high",
      impact: "high",
    },
    {
      id: "risk-margin",
      title: "Supplier cost escalations",
      description: "2 suppliers with >8% QoQ cost increase — could compress margin another 1.5pp.",
      likelihood: "medium",
      impact: "high",
    },
    {
      id: "risk-cash",
      title: "Working capital tied up",
      description: "₹40 Cr in receivables and inventory; promoter ₹4 Cr support bridge is short-term.",
      likelihood: "medium",
      impact: "medium",
    },
    {
      id: "risk-sop",
      title: "Standards and approval evidence gaps",
      description:
        "Quote approvals, ISO readiness evidence, customer standards mapping, and AI output review are not controlled in one auditable workflow.",
      likelihood: "high",
      impact: "medium",
    },
  ],
  topOpportunities: [
    {
      id: "opp-mix",
      title: "Exit low-margin SKUs (3 lines)",
      description: "3 SKUs under 12% GM; repricing or exit could lift blended margin ~1.2pp.",
      impactInr: 1.5 * CR,
      timeframeDays: 90,
    },
    {
      id: "opp-procurement",
      title: "Procurement cost reset on top 2 escalated suppliers",
      description: "Re-tender or alternate sourcing for the 2 escalated suppliers could recover 0.6pp of margin.",
      impactInr: 0.8 * CR,
      timeframeDays: 120,
    },
    {
      id: "opp-ar",
      title: "AR collection drive (₹18 Cr → ₹12 Cr)",
      description: "Aggressive collection + early-payment discount could release ₹6 Cr working capital.",
      impactInr: 6 * CR,
      timeframeDays: 60,
    },
    {
      id: "opp-winrate",
      title: "Win rate lift from 24% to 31%",
      description: "Pricing discipline + technical pre-bid engagement; biggest revenue lever in the plan.",
      impactInr: 16 * CR,
      timeframeDays: 180,
    },
  ],
};

export const demoScenarios: Scenario[] = [
  {
    key: "revenue_plus_10",
    label: "Revenue +10%",
    description: "What would margin, cash, and capacity have to look like to support a 10% revenue lift?",
    currentBaseline: "FY25 actual revenue ₹120 Cr; current run-rate ₹134 Cr.",
    target: "Revenue ₹154 Cr (FY26 plan ₹150 Cr + 2.7% buffer).",
    options: [
      "Lift proposal win rate from 24% to 30%",
      "Aggressive cross-sell into top 5 customers",
      "Add one new product line with proven specs",
    ],
    pros: [
      "Operating leverage: fixed cost spread across more revenue",
      "Improves working-capital cycle if collection discipline is held",
      "Demonstrates growth to board and investors",
    ],
    shortfalls: [
      "Requires capacity headcount addition of ~40 people if not planned",
      "Adds receivable and inventory pressure if mix shifts unfavourably",
      "Cannot be delivered without a 7pp win-rate lift in the funnel",
    ],
    expectedImpact: "₹12 Cr revenue uplift; margin hold to 24% delivers +₹2.9 Cr gross profit.",
    risks: [
      "Cash strain if receivables and inventory scale linearly",
      "Quality slippage if capacity is rushed",
    ],
    recommendation:
      "Pursue a focused top-3 customer expansion first; defer new product line until win-rate is at 28%.",
    confidence: "medium",
  },
  {
    key: "margin_plus_10",
    label: "Margin +10%",
    description: "Where would a 5pp margin lift (21% → 26%) come from?",
    currentBaseline: "FY25 gross margin 21%.",
    target: "FY26 target gross margin 26%.",
    options: [
      "Exit 3 low-margin SKUs",
      "Re-tender top 2 escalated suppliers",
      "Reprice top 5 customer contracts (where contracts permit)",
      "Reduce rework and wastage in the plant",
    ],
    pros: [
      "5pp margin lift = ~₹6 Cr gross profit at FY25 volume",
      "Drops directly to the bottom line",
      "Improves cash by reducing inventory days",
    ],
    shortfalls: [
      "Customer pushback on repricing may cost volume",
      "Suppliers may not move on price in a tight cycle",
      "Exit of SKUs may impact fill-rate on multi-SKU orders",
    ],
    expectedImpact: "₹6 Cr gross profit uplift; blended at 75% retention = ₹4.5 Cr net.",
    risks: [
      "Volume loss on repriced customers",
      "Top-customer churn if exit sequence is mis-managed",
    ],
    recommendation:
      "Sequence: exit low-margin SKUs first, then re-tender suppliers, then reprice — over 6 months.",
    confidence: "high",
  },
  {
    key: "cost_minus_10",
    label: "Cost –10%",
    description: "Which cost lines can defensibly be cut, and at what operational risk?",
    currentBaseline: "FY25 operating cost base ~₹95 Cr.",
    target: "₹9.5 Cr run-rate cost takeout without breaking operations.",
    options: [
      "Consolidate 3 logistics vendors",
      "Renegotiate rent at the 2 oldest sites",
      "Move ERP hosting to managed cloud (capex → opex)",
      "Tighten travel and discretionary spend",
    ],
    pros: [
      "Direct hit to bottom line",
      "Improves cash position quickly",
      "Some items (rent, logistics) are one-time negotiations",
    ],
    shortfalls: [
      "10% across-the-board is unrealistic without headcount",
      "Renegotiation cycles are 90+ days",
      "May damage supplier and landlord relationships if mishandled",
    ],
    expectedImpact: "₹3.5–4.5 Cr achievable in 6 months; remainder needs 9–12 months.",
    risks: [
      "Quality or delivery slippage if cuts go too deep",
      "Vendor churn if renegotiation is heavy-handed",
    ],
    recommendation:
      "Target 5% in 6 months with the logistics + rent + cloud moves; re-evaluate before deeper cuts.",
    confidence: "medium",
  },
  {
    key: "headcount_minus_15",
    label: "Headcount –15%",
    description: "What productivity uplift is required, and where would it come from?",
    currentBaseline: "Headcount 420; revenue per employee ₹28.6L.",
    target: "Headcount 357 (-63) while keeping revenue ≥ ₹120 Cr.",
    options: [
      "Automate manual reporting across 4 functions",
      "Consolidate shifts in the plant",
      "Outsource non-core functions (security, housekeeping, IT helpdesk)",
    ],
    pros: [
      "₹4–5 Cr annualised payroll saving",
      "Raises revenue per employee toward ₹33.6L target",
    ],
    shortfalls: [
      "Risk of execution slowdown in the plant during transition",
      "Severance and rehire cost in the short term",
      "Loss of institutional knowledge in non-core functions",
    ],
    expectedImpact: "₹4.5 Cr payroll saving offset by ₹1.2 Cr severance = ₹3.3 Cr net in Year 1.",
    risks: [
      "Plant downtime during transition",
      "Customer-facing impact if outsourced vendors underperform",
    ],
    recommendation:
      "Defer to a 12-month plan after the win-rate and margin work is underway; do not combine with cost cut.",
    confidence: "low",
  },
  {
    key: "cash_improvement",
    label: "Cash improvement",
    description: "Impact of stretching payables, tightening receivables, or releasing inventory.",
    currentBaseline: "Receivables ₹18 Cr; inventory ₹22 Cr; payables stretched 45 days.",
    target: "Release ₹6–8 Cr working capital over 6 months.",
    options: [
      "AR collection drive with early-payment discount (1% for <30 days)",
      "Inventory rationalisation on slow-moving SKUs",
      "Stretch payables to 60 days with top 5 suppliers",
      "Convert 2 largest customer contracts to milestone billing",
    ],
    pros: [
      "Direct cash release without P&L impact",
      "Improves DSCR and headroom for capex",
      "Reduces interest cost if working-capital line is in use",
    ],
    shortfalls: [
      "Early-payment discounts hit margin",
      "Supplier relationship risk on payables stretch",
      "Inventory write-downs possible on slow movers",
    ],
    expectedImpact: "₹6–8 Cr cash release; ~₹0.3 Cr margin cost on early-payment discount.",
    risks: [
      "Customer churn if collections are too aggressive",
      "Supplier delivery risk if payables are stretched too far",
    ],
    recommendation:
      "Start with AR collection drive and inventory rationalisation; defer payables stretch to month 3.",
    confidence: "high",
  },
];

export const demoRecommendations: Recommendation[] = [
  {
    id: "rec-1",
    rank: 1,
    title: "Lift proposal win rate from 24% to 30%",
    description:
      "Tighten go/no-go discipline, build pre-bid technical engagement, and reprice the bottom 20% of deals. Target: 7 of next 25 proposals won.",
    priority: "P0",
    businessImpact: "₹14 – ₹18 Cr incremental revenue in FY26",
    effort: "medium",
    timeframeDays: 90,
    ownerRole: "CRO + Head of Proposals",
    evidence: "Q3 proposal log shows 24% win rate; board mandate is 31% (board deck p.9).",
    confidence: "high",
  },
  {
    id: "rec-2",
    rank: 2,
    title: "Exit the 3 lowest-margin SKUs",
    description:
      "Formally exit 3 SKUs under 12% GM. Communicate to affected customers with 60-day notice and a fill-rate plan.",
    priority: "P0",
    businessImpact: "₹1.2 – ₹1.8 Cr margin uplift in FY26",
    effort: "low",
    timeframeDays: 60,
    ownerRole: "COO + Sales leadership",
    evidence: "Pipeline tracker margin column flags 3 SKUs (BHF-VLV-110, BHF-VLV-114, BHF-PMP-207).",
    confidence: "high",
  },
  {
    id: "rec-3",
    rank: 3,
    title: "AR collection drive + early-payment discount",
    description:
      "Run a 60-day collection sprint with sales ops; offer 1% early-payment discount to settle open invoices inside 30 days.",
    priority: "P0",
    businessImpact: "₹6 – ₹8 Cr working capital release",
    effort: "low",
    timeframeDays: 60,
    ownerRole: "CFO + AR Lead",
    evidence: "AR aging 31-Dec-2025 = ₹18 Cr; DSO at 55 days vs 35-day target.",
    confidence: "high",
  },
  {
    id: "rec-4",
    rank: 4,
    title: "Create ISO and customer standards readiness evidence register",
    description:
      "Map applicable ISO 9001, ISO 14001, ISO 45001, ISO/IEC 27001, ISO/IEC 42001, ISO 50001, and customer requirements to evidence owners, status, gaps, and review dates.",
    priority: "P1",
    businessImpact: "Documentation readiness and audit evidence visibility.",
    effort: "medium",
    timeframeDays: 45,
    ownerRole: "Quality Head + Compliance Lead",
    evidence:
      "Sample readiness register lacks complete standards applicability, evidence status, and ownership mapping.",
    confidence: "medium",
  },
  {
    id: "rec-5",
    rank: 5,
    title: "Map customer technical standards to proposal and delivery workflows",
    description:
      "Create controlled checkpoints for API, ASME, ANSI, IEC, ISA, and customer-specific requirements from bid review through delivery evidence.",
    priority: "P1",
    businessImpact: "Lower proposal rework and stronger technical evidence readiness.",
    effort: "low",
    timeframeDays: 30,
    ownerRole: "Engineering Head + Proposal Head",
    evidence: "SOP §3.2 + ERP audit log: 7 quotes >₹50L without sign-off in Q3.",
    confidence: "high",
  },
  {
    id: "rec-6",
    rank: 6,
    title: "Move 4 delayed proposals to a fast-track review",
    description:
      "₹6.2 Cr of proposals are >30 days past expected close. Assign a deal owner and 14-day close plan to each.",
    priority: "P1",
    businessImpact: "₹4 – ₹6 Cr revenue recovery in Q4",
    effort: "low",
    timeframeDays: 14,
    ownerRole: "CRO",
    evidence: "Q3 proposal log: 4 proposals >30 days past expected close.",
    confidence: "medium",
  },
  {
    id: "rec-7",
    rank: 7,
    title: "Build supplier qualification and subcontractor governance tracker",
    description:
      "Track qualification status, onboarding documents, performance evidence, exceptions, and review dates for suppliers and subcontractors.",
    priority: "P2",
    businessImpact: "Vendor onboarding readiness and supply-chain risk visibility.",
    effort: "medium",
    timeframeDays: 90,
    ownerRole: "Procurement Head + Quality Head",
    evidence:
      "Supplier cost movements are visible, but qualification, onboarding, and subcontractor governance evidence is missing.",
    confidence: "low",
  },
  {
    id: "rec-8",
    rank: 8,
    title: "Introduce AI output validation and human approval workflow",
    description:
      "Require source-linked review of prompts, outputs, exceptions, and recommendations before any management action; prohibit autonomous irreversible action.",
    priority: "P2",
    businessImpact: "Trusted-agent readiness, accountability, and audit trail coverage.",
    effort: "high",
    timeframeDays: 120,
    ownerRole: "CIO + Risk / Compliance",
    evidence:
      "No complete human validation, prompt/output review, or approval history is present in the sample evidence set.",
    confidence: "medium",
  },
  {
    id: "rec-9",
    rank: 9,
    title: "Create statutory document and audit evidence dashboard",
    description:
      "Index required statutory documents and audit evidence with owner, validity, evidence status, gap, and next review date.",
    priority: "P3",
    businessImpact: "Documentation readiness and management visibility.",
    effort: "low",
    timeframeDays: 30,
    ownerRole: "Company Secretary + Compliance Lead",
    evidence:
      "Statutory document status and audit evidence ownership are not available in one controlled view.",
    confidence: "high",
  },
  {
    id: "rec-10",
    rank: 10,
    title: "Standardize vendor registration and customer prequalification documentation",
    description:
      "Create reusable, version-controlled packs for vendor registration and customer prequalification, linked to proposal and onboarding workflows.",
    priority: "P3",
    businessImpact: "Faster documentation response and fewer onboarding gaps.",
    effort: "low",
    timeframeDays: 7,
    ownerRole: "Commercial Operations + Procurement",
    evidence:
      "Customer prequalification and vendor registration documentation is not included in the current source set.",
    confidence: "high",
  },
];

export const demoPlan: ActionPhase[] = [
  {
    phase: "01",
    windowLabel: "Weeks 1–2",
    title: "Stabilise and stop the bleed",
    description: "Run the quick wins that protect cash and close the most exposed deals.",
    deliverables: [
      "Create standards and customer requirements mapping (recs 4–5)",
      "Open 4 delayed-proposal fast-track reviews (rec 6)",
      "Kick off AR collection drive with 1% early-payment discount (rec 3)",
    ],
  },
  {
    phase: "02",
    windowLabel: "Weeks 3–6",
    title: "Move the revenue and margin numbers",
    description: "Execute the actions that move the FY26 plan numbers.",
    deliverables: [
      "Exit 3 lowest-margin SKUs with customer communications (rec 2)",
      "Run proposal win-rate programme: go/no-go, technical pre-bid, pricing discipline (rec 1)",
      "Launch supplier qualification and subcontractor governance tracker (rec 7)",
    ],
  },
  {
    phase: "03",
    windowLabel: "Weeks 7–10",
    title: "Reprice and restructure",
    description: "Open the harder commercial conversations supported by the new data.",
    deliverables: [
      "Introduce AI output validation and human approval workflow (rec 8)",
      "Create statutory document and audit evidence dashboard (rec 9)",
      "Standardize vendor registration and customer prequalification packs (rec 10)",
    ],
  },
  {
    phase: "04",
    windowLabel: "Weeks 11–13",
    title: "Lock cadence and prepare next cycle",
    description: "Lock the operating cadence and feed the next 48-hour diagnostic.",
    deliverables: [
      "Board review of progress against FY26 plan",
      "Review evidence closure across standards, suppliers, and AI governance",
      "Refresh truth map with Q4 actuals",
    ],
  },
];
