"use client";

import { useParams } from "next/navigation";
import { useAssessmentStore } from "@/stores/assessment";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Brain,
  Printer,
  Building2,
  AlertTriangle,
  Target,
  Lightbulb,
  Rocket,
  Calendar,
  CheckCircle2,
  Users,
  IndianRupee,
} from "lucide-react";

export default function ReportPage() {
  const params = useParams();
  const getAssessment = useAssessmentStore((s) => s.getAssessment);
  const assessment = getAssessment(params.id as string);

  if (!assessment) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center text-muted">
        Assessment not found
      </div>
    );
  }

  const profile = assessment.enterpriseProfile;
  const { cockpit } = assessment;

  return (
    <div className="min-h-screen bg-background">
      <div className="no-print sticky top-0 z-50 border-b border-border bg-white/90 backdrop-blur-md">
        <div className="max-w-5xl mx-auto px-6 h-14 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="h-8 w-8 rounded-lg bg-gradient-to-br from-accent to-cyan flex items-center justify-center">
              <Brain className="h-4 w-4 text-white" />
            </div>
            <div>
              <span className="font-bold text-foreground">PulseIQ Assessment Report</span>
              <span className="text-xs text-muted ml-2 hidden sm:inline">by RightSense Technologies</span>
            </div>
          </div>
          <Button onClick={() => window.print()} size="sm" className="bg-accent hover:bg-accent-hover text-white shadow-sm">
            <Printer className="h-4 w-4 mr-1" />
            Print / Save as PDF
          </Button>
        </div>
      </div>

      <main className="max-w-5xl mx-auto px-6 py-8 space-y-8">
        <div className="text-center border-b border-border pb-8">
          <div className="inline-flex items-center gap-2 rounded-full bg-accent-muted px-4 py-1.5 text-sm text-accent font-medium mb-5">
            <Brain className="h-3.5 w-3.5" />
            PulseIQ Enterprise Intelligence
          </div>
          <h1 className="text-3xl font-bold mb-2 text-foreground">Enterprise Intelligence Assessment</h1>
          <h2 className="text-xl text-foreground-secondary font-semibold">{profile.companyName}</h2>
          <div className="flex items-center justify-center gap-4 mt-3 text-sm text-muted">
            <span className="flex items-center gap-1"><Building2 className="h-3.5 w-3.5" /> {profile.industry}</span>
            <span className="flex items-center gap-1"><IndianRupee className="h-3.5 w-3.5" /> {profile.revenueRange}</span>
            <span className="flex items-center gap-1"><Users className="h-3.5 w-3.5" /> {profile.employeeCount.toLocaleString()} employees</span>
          </div>
          <div className="mt-4 text-xs text-muted">Generated by PulseIQ | RightSense Technologies Pvt Ltd</div>
        </div>

        <section className="print-break">
          <h3 className="text-xl font-bold mb-4 flex items-center gap-2 text-foreground">
            <Building2 className="h-5 w-5 text-accent" />
            Company Profile
          </h3>
          <div className="grid md:grid-cols-2 gap-5">
            <div>
              <h4 className="font-semibold mb-2 text-foreground">Current Systems</h4>
              <div className="space-y-1 text-sm">
                {Object.entries(profile.currentSystems).map(
                  ([key, value]) =>
                    value && (
                      <div key={key} className="flex justify-between py-2 border-b border-border-subtle">
                        <span className="text-muted capitalize font-medium">{key}</span>
                        <span className="font-semibold text-foreground">{value}</span>
                      </div>
                    )
                )}
              </div>
            </div>
            <div>
              <h4 className="font-semibold mb-2 text-foreground">Strategic Priorities</h4>
              <div className="space-y-2">
                {profile.strategicPriorities.map((p, i) => (
                  <div key={i} className="flex items-start gap-2 text-sm">
                    <CheckCircle2 className="h-4 w-4 text-success shrink-0 mt-0.5" />
                    <span className="text-foreground-secondary">{p}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </section>

        <section className="print-break">
          <h3 className="text-xl font-bold mb-4 flex items-center gap-2 text-foreground">
            <AlertTriangle className="h-5 w-5 text-error" />
            Top Bottlenecks
          </h3>
          <div className="space-y-2">
            {cockpit.topBottlenecks.map((b, i) => (
              <div key={i} className="flex items-start gap-3 p-3 rounded-xl bg-error-muted border border-error/10 text-sm">
                <span className="font-bold text-error">{i + 1}.</span>
                <span className="text-foreground">{b}</span>
              </div>
            ))}
          </div>
        </section>

        <section className="print-break">
          <h3 className="text-xl font-bold mb-4 flex items-center gap-2 text-foreground">
            <Lightbulb className="h-5 w-5 text-warning" />
            AI Transformation Opportunities
          </h3>
          <div className="grid md:grid-cols-2 gap-4 mb-4">
            <div className="p-4 rounded-xl bg-accent-muted border border-accent/10">
              <div className="text-2xl font-bold text-accent">{cockpit.opportunityValue}</div>
              <div className="text-sm text-muted">Total Opportunity Value</div>
            </div>
            <div className="p-4 rounded-xl bg-success-muted border border-success/10">
              <div className="text-2xl font-bold text-success">{cockpit.quickWinsCount}</div>
              <div className="text-sm text-muted">Quick Wins</div>
            </div>
          </div>
          <div className="space-y-3">
            {assessment.opportunities.slice(0, 6).map((opp) => (
              <div key={opp.id} className="p-4 rounded-xl border border-border">
                <div className="flex items-center gap-2 mb-1">
                  <Badge
                    variant={
                      opp.priorityTier === "quick_win"
                        ? "success"
                        : opp.priorityTier === "strategic"
                          ? "info"
                          : "outline"
                    }
                    className="font-medium"
                  >
                    {opp.priorityTier.replace("_", " ")}
                  </Badge>
                  <Badge variant="outline" className="font-medium">{opp.impactType.replace("_", " ")}</Badge>
                </div>
                <h4 className="font-semibold text-foreground">{opp.title}</h4>
                <p className="text-sm text-muted mt-1">{opp.description}</p>
                <div className="text-sm mt-2">
                  <span className="font-medium text-muted">Impact: </span>
                  <span className="font-semibold text-foreground">{opp.estimatedImpact}</span>
                </div>
              </div>
            ))}
          </div>
        </section>

        <section className="print-break">
          <h3 className="text-xl font-bold mb-4 flex items-center gap-2 text-foreground">
            <Rocket className="h-5 w-5 text-accent" />
            Future Operating Model
          </h3>
          <div className="space-y-4">
            {assessment.futureModel.map((model) => (
              <div key={model.departmentId} className="p-4 rounded-xl border border-border">
                <h4 className="font-semibold text-foreground mb-2">{model.departmentName}</h4>
                <div className="grid md:grid-cols-2 gap-3 text-sm">
                  <div className="p-3 rounded-xl bg-error-muted border border-error/10">
                    <div className="font-semibold text-error mb-1">Current</div>
                    <span className="text-foreground-secondary">{model.beforeState}</span>
                  </div>
                  <div className="p-3 rounded-xl bg-success-muted border border-success/10">
                    <div className="font-semibold text-success mb-1">Future</div>
                    <span className="text-foreground-secondary">{model.afterState}</span>
                  </div>
                </div>
                <div className="mt-2 text-sm">
                  <span className="font-medium text-muted">AI Agents: </span>
                  <span className="text-foreground font-medium">{model.recommendedAIAgents.join(", ")}</span>
                </div>
              </div>
            ))}
          </div>
        </section>

        <section className="print-break">
          <h3 className="text-xl font-bold mb-4 flex items-center gap-2 text-foreground">
            <Calendar className="h-5 w-5 text-success" />
            30/60/90 Day Roadmap
          </h3>
          <div className="space-y-5">
            {assessment.roadmap.map((phase) => (
              <div key={phase.phase}>
                <h4 className="font-semibold mb-2 text-foreground">{phase.title}</h4>
                <div className="space-y-2">
                  {phase.milestones.map((m) => (
                    <div key={m.id} className="p-3 rounded-xl border border-border text-sm">
                      <div className="font-semibold text-foreground">{m.title}</div>
                      <div className="text-muted mt-1">Owner: {m.ownerFunction} | KPI: {m.measurableKPI}</div>
                    </div>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </section>

        <section>
          <h3 className="text-xl font-bold mb-4 flex items-center gap-2 text-foreground">
            <Target className="h-5 w-5 text-accent" />
            Executive Actions
          </h3>
          <div className="space-y-2">
            {cockpit.executiveActions.map((action, i) => (
              <div key={i} className="flex items-start gap-3 p-3 rounded-xl bg-accent-muted text-sm">
                <span className="font-bold text-accent">{i + 1}.</span>
                <span className="text-foreground">{action}</span>
              </div>
            ))}
          </div>
        </section>

        <footer className="border-t border-border pt-6 text-center text-sm text-muted">
          <div className="flex items-center justify-center gap-2 mb-2">
            <div className="h-6 w-6 rounded-lg bg-gradient-to-br from-accent to-cyan flex items-center justify-center">
              <Brain className="h-3.5 w-3.5 text-white" />
            </div>
            <span className="font-bold text-foreground">PulseIQ Enterprise Intelligence</span>
          </div>
          <div className="text-foreground-secondary">Convert enterprise complexity into AI-native operating intelligence</div>
          <div className="mt-1">Generated by PulseIQ | RightSense Technologies Pvt Ltd</div>
          <div className="text-xs mt-1">pulseiq.co.in</div>
        </footer>
      </main>
    </div>
  );
}
